server:
  port: 8083

spring:
  application:
    name: settlement-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/claims}
    username: ${DB_USERNAME:claims}
    password: ${DB_PASSWORD:claims}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: settlements
    open-in-view: false
  flyway:
    enabled: true
    schemas: settlements
    default-schema: settlements
    create-schemas: true
    table: flyway_schema_history_settlement_service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.sunil.insurance.common.events
        spring.json.value.default.type: com.sunil.insurance.common.events.ClaimApprovedEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
